[workspace]
members = ["."]

[networks.arbitrum-sepolia]
endpoint = "https://sepolia-rollup.arbitrum.io/rpc"
chain_id = 421614

[networks.arbitrum-one]
endpoint = "https://arb1.arbitrum.io/rpc"
chain_id = 42161
